-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 21:54:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema finzen
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `finzen` ;

-- -----------------------------------------------------
-- Schema finzen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finzen` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `finzen` ;

-- -----------------------------------------------------
-- Table `finzen`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finzen`.`Users` ;

CREATE TABLE IF NOT EXISTS `finzen`.`Users` (
  `idUser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT NULL DEFAULT '0',
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `finzen`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finzen`.`Categories` ;

CREATE TABLE IF NOT EXISTS `finzen`.`Categories` (
  `idCategory` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `icon` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `finzen`.`Budgets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finzen`.`Budgets` ;

CREATE TABLE IF NOT EXISTS `finzen`.`Budgets` (
  `idBudget` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUser` INT UNSIGNED NOT NULL,
  `idCategory` INT UNSIGNED NOT NULL,
  `limitAmount` DECIMAL(10,2) NOT NULL,
  `month` CHAR(7) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idBudget`),
  INDEX `idUser` (`idUser` ASC),
  INDEX `idCategory` (`idCategory` ASC),
  CONSTRAINT `Budgets_ibfk_1`
    FOREIGN KEY (`idUser`)
    REFERENCES `finzen`.`Users` (`idUser`)
    ON DELETE CASCADE,
  CONSTRAINT `Budgets_ibfk_2`
    FOREIGN KEY (`idCategory`)
    REFERENCES `finzen`.`Categories` (`idCategory`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `finzen`.`Goals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finzen`.`Goals` ;

CREATE TABLE IF NOT EXISTS `finzen`.`Goals` (
  `idGoal` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUser` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `targetAmount` DECIMAL(10,2) NOT NULL,
  `currentAmount` DECIMAL(10,2) NULL DEFAULT '0.00',
  `deadline` DATE NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idGoal`),
  INDEX `idUser` (`idUser` ASC),
  CONSTRAINT `Goals_ibfk_1`
    FOREIGN KEY (`idUser`)
    REFERENCES `finzen`.`Users` (`idUser`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `finzen`.`Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transactions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `Transactions` (
  `idTransaction` int unsigned NOT NULL AUTO_INCREMENT,
  `idUser` int unsigned NOT NULL,
  `type` enum('income','expense') COLLATE utf8mb4_unicode_ci NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `idCategory` int unsigned DEFAULT NULL,
  `date` date NOT NULL,
  `balance` decimal(10,2) NOT NULL,
  PRIMARY KEY (`idTransaction`),
  KEY `idUser` (`idUser`),
  KEY `idCategory` (`idCategory`),
  CONSTRAINT `Transactions_ibfk_1` FOREIGN KEY (`idUser`) REFERENCES `Users` (`idUser`) ON DELETE CASCADE,
  CONSTRAINT `Transactions_ibfk_2` FOREIGN KEY (`idCategory`) REFERENCES `Categories` (`idCategory`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=901 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
